customs/customs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('testapp/', include('testapp.urls')),
    path('admin/', admin.site.urls),
]

customs/testapp/urls.py
from django.urls import path
from . import views
from .views import DataxListView
app_name = 'testapp'

urlpatterns = [path('', views.index, name='index'),
               path("datax/", DataxListView.as_view()),
               path('datax/<int:year>/', views.detail, name='detail'),
               path('upload/', views.upload, name='upload')
              # path("datax/<int:id>/update/", views.datax_chakan.as_view()),
               ]

customs/testapp/forms.py
from django import forms


class FileUploadForm(forms.Form):
    #name = forms.CharField(max_length=20, min_length=3, required=True, label='名称:')
    #my_file = forms.FileField(label='文件名称:', style="font-size: 30px;")
    #选择文件样式：style="font-size:17px; color:red; margin-left:2%"
    my_file = forms.FileField(label='文件名称:')

customs/testapp/views.py
import csv

from django.shortcuts import render
# Create your views here.
from .models import Datax, Dataxx
from django.http import HttpResponse, HttpResponseRedirect
from testapp.querysets import QuerySets
from django.template import loader
from django_tables2 import SingleTableView
from .tables import DataxTable
from django.views.generic.edit import BaseDetailView, UpdateView
from django.http import Http404
from .forms import FileUploadForm
import xlrd
from testapp.excelHandler import ExcelRead
from testapp.coreAlgrithm import coreTax

def index(request):
    result = dict()
    qs = QuerySets()
    qs.handle_elements_list('0000', '0001')
    result = qs.handle_dict()
    x = dict()
    y = dict()
    x = qs.change_original_dict()
    y = qs.tax_result(x)
    dict_groups = []
    for key, values in x.items():
        tags = y.get(key)
        if len(tags) == 0 or len(tags) != len(values):
            print("数据字典和标记字典不对应！")
            break
        for i in range(len(values)):
            values[i].name = tags[i]
            jiba = Datax.objects.get(id=values[i].id)
            jiba.name = tags[i]
            # jiba.save()
            dict_groups.append(values[i])
            # dict_groups.append([values[i]] + [tags[i]])
    return render(request, 'testapp/index.html', {'context': dict_groups})


class DataxListView(SingleTableView):
    core = coreTax()
    z = core.tax_algorithm()
    model = Datax
    table_class = DataxTable
    table_data = z
    # table_class.order_by = "product_id"
    template_name = 'testapp/test.html'


def detail(request, year):
    try:
        question = Datax.objects.get(pk=year)
    except question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'testapp/detail.html', {'question': question})


def upload(request):
    """
    :param request:
    :return: 上传文件excel表格 ,并进行解析
    """
    if request.method == "POST":
        print("post request")
        myform = FileUploadForm(request.POST, request.FILES)
        # 在这里可以添加筛选excel的机制
        if myform.is_valid():
            erli = []
            f = request.FILES['my_file']
            path = f.temporary_file_path()
            nessEle = ["海关编号", "商品序号", "商品编号", "商品名称", "规格型号"]
            er = ExcelRead()
            if path.endswith('.xls'):
                wb = xlrd.open_workbook(filename=None, file_contents=f.read())  # 关键点在于这里
                table = wb.sheets()[0]
                er.list_data(erli, table, table.nrows)
                er.handle_uploaded_file(erli)
            if path.endswith('.csv'):
                # csv格式读取数据，f为上传的文件
                with open(path, newline='') as rfile:
                    reader = csv.reader(rfile, dialect='excel')
                    # 读取第二行数据（表头为第一行）
                    header_row = next(reader)
                    if set(header_row) >= set(nessEle):
                        return
                    for line in reader:
                        erli.append(line)
                    print("erli==={}".format(erli[0]))
                    # er.handle_uploaded_file(erli)
            print("导入data0表成功！！！")
        return render(request, "testapp/fileup.html")
    else:
        myform = FileUploadForm()
    return render(request, 'testapp/fileup.html', context={'form': myform, 'what': "文件传输"})

customs/testapp/templates/testapp/detail.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>数据详情</title>
	<link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
	<script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<form class="form-horizontal" role="form">
    {% if question %}
	<div class="form-group">
		<label class="col-sm-2 control-label">海关编号</label>
		<div class="col-sm-4">
			<p class="form-control-static">{{ question.customs_id }}</p>
		</div>
        <label class="col-sm-2 control-label">商品序号</label>
        <div class="col-sm-4">
            <p class="form-control-static">{{ question.product_id }}</p>
        </div>
	</div>
	<div class="form-group">
		<label class="col-sm-2 control-label">商品编号</label>
		<div class="col-sm-4">
			<p class="form-control-static">{{ question.product_number }}</p>
		</div>
        <label class="col-sm-2 control-label">商品名称</label>
        <div class="col-sm-4">
            <p class="form-control-static">{{ question.product_name }}</p>
        </div>
	</div>

                 <div class="form-group">
                    <label for="schoolName" class="col-sm-2 control-label">商品规格型号</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="schoolName" name="schoolName" placeholder= {{ question.guige }} readonly="true">
                    </div>
                </div>
	<div class="form-group">
		<label class="col-sm-2 control-label">第一法定计量单位</label>
		<div class="col-sm-4">
			<p class="form-control-static">{{ question.diyi_jiliang }}</p>
		</div>
        <label class="col-sm-2 control-label">第一法定数量</label>
        <div class="col-sm-4">
            <p class="form-control-static">{{ question.diyi_shuliang }}</p>
        </div>
	</div>

	<div class="form-group">
		<label class="col-sm-2 control-label">申报日期</label>
		<div class="col-sm-2">
			<p class="form-control-static">{{ question.shenbao_date }}</p>
		</div>
        <label class="col-sm-2 control-label">申报单位代码</label>
        <div class="col-sm-2">
            <p class="form-control-static">{{ question.shenbao_code }}</p>
        </div>
        <label class="col-sm-2 control-label">申报单位名称</label>
        <div class="col-sm-2">
            <p class="form-control-static">{{ question.shenbao_name }}</p>
        </div>
	</div>

    	<div class="form-group">
		<label class="col-sm-2 control-label">每项商品需要监管证件</label>
		<div class="col-sm-4">
			<p class="form-control-static">email@example.com</p>
		</div>
        <label class="col-sm-2 control-label">监管方式</label>
        <div class="col-sm-4">
            <p class="form-control-static">唉</p>
        </div>
	</div>

    <div class="form-group">
		<label class="col-sm-2 control-label">货主单位名称</label>
		<div class="col-sm-4">
			<p class="form-control-static">{{ question.huozhu_name }}</p>
		</div>
        <label class="col-sm-2 control-label">货主单位代码</label>
        <div class="col-sm-4">
            <p class="form-control-static">{{ question.huozhu_code }}</p>
        </div>
	</div>

    <div class="form-group">
                    <label for="userId" class="col-sm-2 control-label">应征从价关税率</label>
                    <div class="col-sm-2">
                        <input type="text"  class="form-control"  name="userId" placeholder={{ question.ying_jia_guan }} readonly="true">
                    </div>
                    <label for="age" class="col-sm-2 control-label">实征从价关税率</label>
                    <div class="col-sm-2">
                        <input type="text" class="form-control"  name="age" placeholder="{{ question.shi_jia_guan }}" readonly="true">
                    </div>
    </div>

        <div class="form-group">
                    <label for="userId" class="col-sm-2 control-label">应征从量关税税率</label>
                    <div class="col-sm-2">
                        <input type="text"  class="form-control"  name="userId" placeholder={{ question.ying_liang_guan }} readonly="true">
                    </div>
                    <label for="age" class="col-sm-2 control-label">实征从量关税税率</label>
                    <div class="col-sm-2">
                        <input type="text" class="form-control"  name="age" placeholder={{ question.shi_liang_guan }} readonly="true">
                    </div>
    </div>

        <div class="form-group">
                    <label for="userId" class="col-sm-2 control-label">应征从价增值税率</label>
                    <div class="col-sm-2">
                        <input type="text"  class="form-control" name="userId" placeholder={{ question.ying_jia_zeng }} readonly="true">
                    </div>
                    <label for="age" class="col-sm-2 control-label">实征从价增值税率</label>
                    <div class="col-sm-2">
                        <input type="text" class="form-control" name="age" placeholder={{ question.shi_jia_zeng }} readonly="true">
                    </div>
    </div>

        <div class="form-group">
                    <label for="userId" class="col-sm-2 control-label">应征从价消费税率</label>
                    <div class="col-sm-2">
                        <input type="text"  class="form-control" name="userId" placeholder={{ question.ying_jia_xiao }} readonly="true">
                    </div>
                    <label for="age" class="col-sm-2 control-label">实征从价消费税率</label>
                    <div class="col-sm-2">
                        <input type="text" class="form-control" name="age" placeholder={{ question.shi_jia_xiao }} readonly="true">
                    </div>
    </div>

        <div class="form-group">
                    <label for="userId" class="col-sm-2 control-label">应征从量消费税税率</label>
                    <div class="col-sm-2">
                        <input type="text"  class="form-control" name="userId" placeholder={{ question.ying_liang_xiao }} readonly="true">
                    </div>
                    <label for="age" class="col-sm-2 control-label">实征从量消费税税率</label>
                    <div class="col-sm-2">
                        <input type="text" class="form-control" name="age" placeholder={{ question.shi_liang_xiao }} readonly="true">
                    </div>
    </div>

        <div class="form-group">
                    <label for="userId" class="col-sm-2 control-label">应征从价反倾销税税率</label>
                    <div class="col-sm-2">
                        <input type="text"  class="form-control" id="userId" name="userId" placeholder={{ question.ying_jia_fan }} readonly="true">
                    </div>
                    <label for="age" class="col-sm-2 control-label">实征从价反倾销税税率</label>
                    <div class="col-sm-2">
                        <input type="text" class="form-control" id="age" name="age" placeholder={{ question.shi_jia_fan }} readonly="true">
                    </div>
    </div>




	<div class="form-group">
		<label class="col-sm-2 control-label">产销国</label>
		<div class="col-sm-2">
			<p class="form-control-static">{{ question.chanxiaoguo }}</p>
		</div>
        <label class="col-sm-2 control-label">关税完税价</label>
		<div class="col-sm-2">
			<input type="password" class="form-control"
				   placeholder={{ question.shui_jia }} >
		</div>
	</div>

{% else %}
    <p>没有这项数据</p>
{% endif %}
</form>
</body>
</html>

customs/testapp/templates/testapp/fileup.html
    <div class="container">
        <div class="row">

            <div class="col-md-8 col-md-offset-2">
                <div><h3 style="text-align: center; font-size:35px;">{{what}}</h3></div>
                <form method="post" enctype="multipart/form-data" action="{% url 'testapp:upload' %}"
                      class="table table-bordered form-horizontal" style="margin-top: 5%;margin-left: 35%;">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" value="点击提交"
                           style="margin-left: 12%;margin-top: 3%;background-color: #00FF99;font-size: 25px;"/>
                </form>

            </div>

        </div>
    </div>

customs/testapp/templates/testapp/index.html
{% if context %}
    <table>

             {% for val in context %}

        <tr>

<!--            <td>david</td>-->
                    <td>{{ val.product_number }}</td>
                    <td>{{ val.product_id }}</td>
                    <td>{{ val.product_name }}</td>
                    <td>{{ val.guige }}</td>
                    <td>{{ val.shi_jia_guan }}</td>
                    <td>{{  val.tag }}</td>
        </tr>
              {% endfor %}

    </table>
{% else %}
    <p>字典无值.</p>
{% endif %}

customs/testapp/templates/testapp/test.html
{# testapp/templates/testapp/people.html #}
{% load render_table from django_tables2 %}
<html>
    <head>
        <title>Datax表</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    </head>
    <body>
        {% render_table table %}
    </body>
</html>